version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
    logging:
      driver: syslog
      options:
        tag: nginx
    ports:
      - 80:80
      - 443:443
    links:
      #- postgres
      - mariadb
      - ciboard
    volumes:
      - ./nginx/conf:/etc/nginx
      - ./nginx/logs:/var/log/nginx
      #- ./nginx/html:/var/www/html
      - ./ciboard/public_html:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt

  #postgres:
  #  container_name: postgres
  #  image: postgres:alpine
  #  restart: unless-stopped
  #  environment:
  #    - POSTGRES_PASSWORD=p@ssw0rd
  #    - TZ=Asia/Seoul
  #  logging:
  #    driver: syslog
  #    options:
  #      tag: postgresql
  #  #ports:
  #  #  - 5432:5432
  #  expose:
  #    - 5432
  #  volumes:
  #    - ./postgres/initdb:/docker-entrypoint-initdb.d
  #    - ./postgres/data:/var/lib/postgresql/data

  mariadb:
    container_name: mariadb
    build:
      context: mariadb
    #image: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssw0rd
    logging:
      driver: syslog
      options:
        tag: mariadb
    #ports:
    #  - 3306:3306
    expose:
      - 3306
    volumes:
      - ./mariadb/data:/var/lib/mysql

  ciboard:
    container_name: ciboard
    build:
      context: ciboard
    #image: php:fpm-alpine
    restart: unless-stopped
    environment:
      - CIBOARD_BASEURL=http://192.168.98.122
      - CIBOARD_DB_MYSQL=mariadb
      - CIBOARD_DB_DATABASE=ciboard
      - CIBOARD_DB_USERNAME=ciboard
      - CIBOARD_DB_PASSWORD=ciboard
      - CIBOARD_SECRET_KEY=s3cr3tk3y
      - TZ=Asia/Seoul
    logging:
      driver: syslog
      options:
        tag: ciboard
    #ports:
    #  - 9000:9000
    expose:
      - 9000
    links: 
      #- postgres
      - mariadb
    volumes:
      - ./ciboard/php.ini:/usr/local/etc/php/php.ini
      - ./ciboard/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-docker.conf
      - ./ciboard/public_html:/var/www/html

